name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Atualizado para a versão v3 (mais recente)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: RogerTheRoger
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Atualizado para a versão v4 (mais recente)
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
